# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(7, 7)
tensor_A, tensor_A.shape

(tensor([[0.6076, 0.5206, 0.1163, 0.7601, 0.5612, 0.1372, 0.1966],
         [0.1903, 0.3862, 0.5009, 0.2085, 0.1391, 0.6782, 0.7168],
         [0.6827, 0.4538, 0.7674, 0.4184, 0.8282, 0.1104, 0.9858],
         [0.2808, 0.8104, 0.4382, 0.0245, 0.7087, 0.0680, 0.0138],
         [0.8724, 0.1479, 0.8567, 0.2694, 0.3030, 0.3855, 0.9905],
         [0.8551, 0.3558, 0.7175, 0.3364, 0.4432, 0.7947, 0.1346],
         [0.2186, 0.4131, 0.0901, 0.5582, 0.7190, 0.4797, 0.8200]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor
tensor_B = torch.rand(1, 7)

# Perform matrix multiplication 
torch.mm(tensor_A, tensor_B.T), torch.mm(tensor_A, tensor_B.T).shape

(tensor([[1.4008],
         [1.4749],
         [2.1425],
         [0.9708],
         [1.9791],
         [1.5929],
         [1.5980]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_C = torch.rand(7, 7)
tensor_D = torch.rand(1, 7)

# Matrix multiply tensors
torch.mm(tensor_C, tensor_D.T), torch.mm(tensor_C, tensor_D.T).shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [33]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [45]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_on_gpu_A = torch.rand((2, 3)).to(device)
tensor_on_gpu_B = torch.rand((2, 3)).to(device)
tensor_on_gpu_A, tensor_on_gpu_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [47]:
# Perform matmul on tensor_A and tensor_B
tensor_on_gpu_AB = torch.mm(tensor_on_gpu_A, tensor_on_gpu_B.T)
tensor_on_gpu_AB

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [51]:
# Find max
_max = tensor_on_gpu_AB.max()

# Find min
_min = tensor_on_gpu_AB.min()

_max, _min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [52]:
# Find arg max
argmax = tensor_on_gpu_AB.argmax()

# Find arg min
argmin = tensor_on_gpu_AB.argmin()

argmin, argmax

(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [50]:
# Set seed
torch.manual_seed(1024)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random_tensor_squeezed = random_tensor.squeeze()

# Print out tensors and their shapes
random_tensor, random_tensor.shape, random_tensor_squeezed, random_tensor_squeezed.shape

(tensor([[[[0.8090, 0.7935, 0.2099, 0.9279, 0.8136, 0.7422, 0.4769, 0.4955,
            0.3602, 0.1178]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.8090, 0.7935, 0.2099, 0.9279, 0.8136, 0.7422, 0.4769, 0.4955, 0.3602,
         0.1178]),
 torch.Size([10]))